### ISSUE TITLE
command failed issue

### ISSUE THREAD

**Issue by Hazuki-san** [SirLennox/invalidbotter#1]
```
npm ERR! code 1
npm ERR! path C:\Git\invalidbotter
npm ERR! command failed
npm ERR! command C:\windows\system32\cmd.exe /d /s /c "node build/main.js"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Aoba\AppData\Local\npm-cache\_logs\2020-11-21T14_36_44_490Z-debug.log

C:\Git\invalidbotter>_
```

How can I fix this? Do you have any clue?

**Comment by SirLennox** [comment]
Try to use PowerShell or don't start it with adminstrator, because you are in System32. I have to do more fixes after releasing the npm variant you can use it easilier. Only wait a moment or do it without adminstrator. Thank you for your issue, for more questions write them below.

**Comment by Hazuki-san** [comment]
That CMD is not administrator console...

**Comment by Hazuki-san** [comment]
solved, because it's updated.
